import type { Metadata } from 'next';
import './globals.css';
import ThemeProvider from '@/providers/ThemeProvider';
import { MessageBoxProvider } from '@/providers/MessageBoxProvider';
import WalletInfo from '@/components/wallet';
import WalletProvider from '@/providers/WalletProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={`antialiased`}>
        <ThemeProvider>
          <WalletProvider>
            <MessageBoxProvider>
              <WalletInfo />
              {children}
            </MessageBoxProvider>
          </WalletProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
